In [1]:
import os
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

import pandas as pd
from sklearn.ensemble import RandomForestClassifier, forest
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from IPython.display import display
import numpy as np
import scipy
import re

/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)

In [2]:
train = pd.read_csv('df1.csv')
print('Training set loaded')
print(train.shape)

Training set loaded
(16000, 115)

In [3]:
train

,Unnamed: 0,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,...,OsBuildLab3,OsBuildLab4,OsBuildLab5,Census_OSVersion0,Census_OSVersion1,Census_OSVersion2,Census_OSVersion3,Census_OSVersion4,Census_OSVersion5,HasExistsNotSet
0,60584,60584,1,38,38,3161,0,7.0,0,1632.0,...,11,180502,1908,10,0,16299,547,-1,-1,False
1,94492,94492,1,38,20,3469,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,1,-1,-1,False
2,30969,30969,1,38,14,3444,0,7.0,0,1632.0,...,8,170317,1834,10,0,15063,1155,-1,-1,True
3,48707,48707,1,39,38,3816,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,228,-1,-1,False
4,74948,74948,1,38,38,3292,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,228,-1,-1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,44837,44837,1,35,31,2751,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,1,-1,-1,False
15996,84000,84000,1,38,38,3189,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,48,-1,-1,False
15997,93977,93977,1,38,34,3349,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,165,-1,-1,False
15998,29474,29474,1,38,38,3508,0,7.0,0,1632.0,...,13,180410,1804,10,0,17134,165,-1,-1,False
15999,39434,39434,1,38,16,3481,0,7.0,0,1632.0,...,11,180502,1908,10,0,16299,492,-1,-1,False

In [4]:
df1, drop = train.drop('Unnamed: 0', axis=1), train['Unnamed: 0']

In [5]:
X, Y = df1.drop('HasDetections', axis=1), df1['HasDetections']

In [6]:
import lightgbm as lgb

/python3.7/site-packages/lightgbm/__init__.py:48: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)

In [7]:
m = lgb.LGBMClassifier()
%time m.fit(X, Y)

CPU times: user 13min 59s, sys: 47.4 s, total: 14min 46s
Wall time: 7min 15s

LGBMClassifier(bagging_fraction=0.8, bagging_freq=5, bagging_seed=11,
               boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               feature_fraction=0.8, importance_type='split', lambda_l1=0.15,
               lambda_l2=0.15, learning_rate=0.02, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001,
               min_data_in_leaf=42, min_split_gain=0.0, n_estimators=100,
               n_jobs=-1, num_leaves=31, objective=None, random_state=None,
               reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [8]:
test = pd.read_csv('test.csv')

In [9]:
testing, drop = test.drop('Unnamed: 0', axis=1), test['Unnamed: 0']

In [10]:
X_test, Y_test = testing.drop('HasDetections', axis=1), testing['HasDetections']

In [11]:
%time Y_predi = m.predict(X_test)

CPU times: user 1min 8s, sys: 137 ms, total: 1min 8s
Wall time: 11.1 s

In [12]:
Y_predi = Y_predi.reshape(Y_predi.shape[0], 1)
print(Y_predi)

[[1]
 [0]
 [1]
 ...
 [0]
 [1]
 [1]]

In [13]:
Y_prediction = pd.DataFrame(Y_predi)

In [14]:
Y_prediction

       0
0      1
1      0
2      1
3      0
4      0
...   ..
19995  0
19996  0
19997  0
19998  1
19999  1

[20000 rows x 1 columns]

In [15]:
Y_prediction.to_csv('Prediction1.csv')